### ISSUE TITLE
wrong path inside a namespace if useslash=true

### ISSUE THREAD

**Issue by towe** [chimeric/dokuwiki-plugin-snippets#1]
If the configuration option useslash is set to true (1) and snippets are called inside a namespace, the snippet-overview is not found, i.e. editing

```
http://mydomain.tld/playground/playground?do=edit&rev=
```

and clicking on the snippet-icon calls

```
http://mydomain.tld/playground/lib/plugins/snippets/exe/snippets.php?ns=playground
```

instead of

```
http://mydomain.tld/lib/plugins/snippets/exe/snippets.php?ns=playground
```

**Comment by chimeric** [comment]
Can you check this with the new version?

**Comment by towe** [comment]
sorry for the delay, had to upgrade first... works like a charm, thanks!
