### ISSUE TITLE
Replacing placeholders

### ISSUE THREAD

**Issue by marculfig** [chimeric/dokuwiki-plugin-snippets#4]
Hi,

i like your plugin.
After a time of useing it, i miss the possibility to use placeholders like in the content templates.
Is it possible to add this feature?

bye

**Comment by marculfig** [comment]
Hi,
i tried the Replacement patterns on this side: http://www.dokuwiki.org/namespace_templates
bye...
Marc

**Comment by marculfig** [comment]
Hi again,

i am sorry, i closed this request erroneously.

**Comment by bug** [comment]
Agreed, I miss the placeholders of DokuWiki's namespace templates too. I copied over the templates we already had in our wiki for some namespaces thinking the snippets plugin could make these templates available in the whole wiki. It does so, but the strftime patterns or the @USER@ pattern do no longer get expanded :-(

Anyway Chi, thanks for this nice plugin.
