### ISSUE TITLE
snippets produces zero results

### ISSUE THREAD

**Issue by ghost** [chimeric/dokuwiki-plugin-snippets#5]
I believe I have correctly configured DokuWiki, snippets and other plugins correctly. Everything but snippets seems to be running fine.

The snippets icon is on the edit page menu.
When clicked the snippets window comes up and shows the content of the snippets file.
When a named snippet is clicked, nothing appears in the right side of the of the snippets popup.
Nothing is copied to the page being edited.

I've run DokuWiki for a while now.
I've used snippets before, successfully.

My DokuWiki instance is installed at:
{docroot}/wiki

I know that I've had DokuWiki with snippets running in:
{docroot}/
Might this be a problem?

Output of ~~INFO:{all options} is here:
http://www.bigupload.com/en/file/5228/info-html.tgz.html
44KB

Thanks in advance for any suggestions you can offer.

**Comment by lupo49** [comment]
Please have a look here: http://forum.dokuwiki.org/thread/6929

**Comment by ghost** [comment]
no longer relevant
